// ═════════════════════════════════════════════════════════════════════════════
// METRICS REGISTRY SERVICE — Dynamic metrics definitions by database type
// ═════════════════════════════════════════════════════════════════════════════

const METRIC_DEFINITIONS = {
    postgresql: [
        {
            id: 'cache_hit_ratio',
            label: 'Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * sum(heap_blks_hit) / NULLIF(sum(heap_blks_hit + heap_blks_read), 0), 2) FROM pg_statio_user_tables`,
            thresholds: { warning: 90, critical: 80 },
            description: 'Percentage of heap blocks served from cache vs disk',
        },
        {
            id: 'active_connections',
            label: 'Active Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity WHERE state = 'active'`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of actively executing connections',
        },
        {
            id: 'transactions_per_sec',
            label: 'TPS',
            unit: 'tx/s',
            category: 'performance',
            query: `SELECT ROUND((sum(xact_commit) + sum(xact_rollback)) / EXTRACT(EPOCH FROM (now() - stats_reset)), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Transactions committed and rolled back per second',
        },
        {
            id: 'deadlock_count',
            label: 'Deadlocks',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(deadlocks) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Total number of deadlocks detected',
        },
        {
            id: 'replication_lag',
            label: 'Replication Lag',
            unit: 'bytes',
            category: 'replication',
            query: `SELECT COALESCE(MAX(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)), 0) FROM pg_replication_slots`,
            thresholds: { warning: 52428800, critical: 104857600 },
            description: 'WAL bytes behind on replica (50MB warning, 100MB critical)',
        },
        {
            id: 'dead_tuples_ratio',
            label: 'Dead Tuple Ratio',
            unit: '%',
            category: 'maintenance',
            query: `SELECT ROUND(100.0 * sum(n_dead_tup) / NULLIF(sum(n_live_tup + n_dead_tup), 0), 2) FROM pg_stat_user_tables`,
            thresholds: { warning: 10, critical: 20 },
            description: 'Percentage of dead tuples across all tables',
        },
        {
            id: 'db_size',
            label: 'Database Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT pg_database_size(current_database())`,
            thresholds: { warning: 10737418240, critical: 21474836480 },
            description: 'Total size of the current database (10GB warning, 20GB critical)',
        },
        {
            id: 'index_hit_ratio',
            label: 'Index Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * sum(idx_blks_hit) / NULLIF(sum(idx_blks_hit + idx_blks_read), 0), 2) FROM pg_statio_user_indexes`,
            thresholds: { warning: 95, critical: 85 },
            description: 'Percentage of index blocks served from cache',
        },
        {
            id: 'longest_transaction',
            label: 'Longest Transaction',
            unit: 'seconds',
            category: 'health',
            query: `SELECT EXTRACT(EPOCH FROM max(NOW() - xact_start)) FROM pg_stat_activity WHERE xact_start IS NOT NULL`,
            thresholds: { warning: 300, critical: 900 },
            description: 'Duration of longest running transaction (5min warning, 15min critical)',
        },
        {
            id: 'wal_generation_rate',
            label: 'WAL Generation',
            unit: 'bytes/s',
            category: 'replication',
            query: `SELECT ROUND(pg_wal_lsn_diff(pg_current_wal_lsn(), '0/0') / EXTRACT(EPOCH FROM (now() - pg_postmaster_start_time())), 2)`,
            thresholds: { warning: 10485760, critical: 20971520 },
            description: 'WAL generation rate (10MB/s warning, 20MB/s critical)',
        },
        {
            id: 'temp_files_size',
            label: 'Temp Files',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT COALESCE(sum(temp_files), 0) FROM pg_stat_statements WHERE temp_files > 0`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Total size of temporary files created (1GB warning, 5GB critical)',
        },
        {
            id: 'vacuum_running',
            label: 'Active Vacuums',
            unit: 'count',
            category: 'maintenance',
            query: `SELECT count(*) FROM pg_stat_activity WHERE query ILIKE '%VACUUM%'`,
            thresholds: { warning: 2, critical: 4 },
            description: 'Number of active VACUUM operations',
        },
    ],
    mysql: [
        {
            id: 'innodb_buffer_hit_ratio',
            label: 'InnoDB Buffer Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_read_requests'))), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_reads'`,
            thresholds: { warning: 95, critical: 85 },
            description: 'Percentage of InnoDB buffer pool reads from cache',
        },
        {
            id: 'innodb_buffer_pool_utilization',
            label: 'InnoDB Buffer Pool Utilization',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (pool_size - free_buffers) / pool_size, 2) FROM information_schema.innodb_buffer_pool_stats`,
            thresholds: { warning: 85, critical: 95 },
            description: 'Percentage of InnoDB buffer pool currently in use',
        },
        {
            id: 'innodb_log_waits',
            label: 'InnoDB Log Waits',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_log_waits'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of waits due to InnoDB log buffer being full',
        },
        {
            id: 'innodb_deadlocks',
            label: 'InnoDB Deadlocks',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_deadlocks'`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Total number of InnoDB deadlocks detected',
        },
        {
            id: 'innodb_data_reads',
            label: 'InnoDB Data Reads/sec',
            unit: 'reads/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_reads'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'InnoDB physical data reads per second',
        },
        {
            id: 'innodb_data_writes',
            label: 'InnoDB Data Writes/sec',
            unit: 'writes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_writes'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'InnoDB physical data writes per second',
        },
        {
            id: 'threads_running',
            label: 'Threads Running',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_running'`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of threads currently executing queries',
        },
        {
            id: 'threads_cached',
            label: 'Threads Cached',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_cached'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of cached threads ready to handle new connections',
        },
        {
            id: 'threads_connected',
            label: 'Threads Connected',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_connected'`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of open connections',
        },
        {
            id: 'max_used_connections',
            label: 'Max Used Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Max_used_connections'`,
            thresholds: { warning: 100, critical: 150 },
            description: 'Maximum number of connections used at any time',
        },
        {
            id: 'aborted_connections',
            label: 'Aborted Connections',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Aborted_connects'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of connections aborted due to client not closing properly',
        },
        {
            id: 'aborted_clients',
            label: 'Aborted Clients',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Aborted_clients'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of connections aborted due to client dead or timeout',
        },
        {
            id: 'com_select',
            label: 'SELECT Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_select'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'SELECT statements executed per second',
        },
        {
            id: 'com_insert',
            label: 'INSERT Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_insert'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'INSERT statements executed per second',
        },
        {
            id: 'com_update',
            label: 'UPDATE Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_update'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'UPDATE statements executed per second',
        },
        {
            id: 'com_delete',
            label: 'DELETE Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_delete'`,
            thresholds: { warning: 50, critical: 200 },
            description: 'DELETE statements executed per second',
        },
        {
            id: 'bytes_sent',
            label: 'Bytes Sent/sec',
            unit: 'bytes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Bytes_sent'`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Bytes sent to all clients per second',
        },
        {
            id: 'bytes_received',
            label: 'Bytes Received/sec',
            unit: 'bytes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Bytes_received'`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Bytes received from all clients per second',
        },
        {
            id: 'innodb_row_lock_time_avg',
            label: 'InnoDB Avg Row Lock Wait Time',
            unit: 'ms',
            category: 'health',
            query: `SELECT ROUND(VARIABLE_VALUE / NULLIF((SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_waits'), 0), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_time'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average time in milliseconds for InnoDB row lock waits',
        },
        {
            id: 'innodb_rows_read_per_sec',
            label: 'InnoDB Rows Read/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_read'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'InnoDB rows read per second',
        },
        {
            id: 'innodb_rows_inserted_per_sec',
            label: 'InnoDB Rows Inserted/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_inserted'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'InnoDB rows inserted per second',
        },
        {
            id: 'binary_log_space',
            label: 'Binary Log Space',
            unit: 'bytes',
            category: 'replication',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Binlog_cache_disk_use'`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Cumulative space used by binary logs (1GB warning, 5GB critical)',
        },
        {
            id: 'binlog_cache_disk_use',
            label: 'Binlog Cache Disk Use',
            unit: 'count',
            category: 'replication',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Binlog_cache_disk_use'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of transactions using disk cache for binary log',
        },
        {
            id: 'open_files',
            label: 'Open Files',
            unit: 'count',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Open_files'`,
            thresholds: { warning: 1000, critical: 2000 },
            description: 'Number of currently open files',
        },
        {
            id: 'open_tables',
            label: 'Open Tables',
            unit: 'count',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Open_tables'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Number of currently open tables',
        },
        {
            id: 'table_locks_waited',
            label: 'Table Locks Waited',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Table_locks_waited'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of table lock requests that required waits',
        },
        {
            id: 'handler_read_rnd_next',
            label: 'Full Table Scans/sec',
            unit: 'scans/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Handler_read_rnd_next'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of full table scans per second (indicator of inefficient queries)',
        },
        {
            id: 'key_buffer_hit_ratio',
            label: 'Key Buffer Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Key_read_requests'))), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Key_reads'`,
            thresholds: { warning: 95, critical: 85 },
            description: 'MyISAM key buffer hit ratio (higher is better)',
        },
        {
            id: 'sort_merge_passes',
            label: 'Sort Merge Passes',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Sort_merge_passes'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of merge passes required by the sort algorithm',
        },
        {
            id: 'select_full_join',
            label: 'Full Joins Without Index',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Select_full_join'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of full joins performed without using indexes',
        },
        {
            id: 'slow_queries',
            label: 'Slow Queries',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Slow_queries'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of queries exceeding long_query_time',
        },
        {
            id: 'innodb_row_lock_waits',
            label: 'Row Lock Waits',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_waits'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of InnoDB row lock waits',
        },
        {
            id: 'questions_per_sec',
            label: 'Queries/sec',
            unit: 'q/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Questions'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Questions (statements) per second',
        },
        {
            id: 'table_open_cache_misses',
            label: 'Table Open Cache Misses',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Table_open_cache_misses'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of table open cache misses',
        },
        {
            id: 'replication_lag_seconds',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'replication',
            query: `SHOW SLAVE STATUS`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Seconds behind master in replication',
        },
        {
            id: 'tmp_disk_tables',
            label: 'Temp Disk Tables',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Created_tmp_disk_tables'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of temporary tables created on disk',
        },
    ],
    mssql: [
        {
            id: 'page_life_expectancy',
            label: 'Page Life Expectancy',
            unit: 'seconds',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Page life expectancy'`,
            thresholds: { warning: 300, critical: 100 },
            description: 'Average lifetime in cache of buffer pages (higher is better)',
        },
        {
            id: 'buffer_cache_hit_ratio',
            label: 'Buffer Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * a.cntr_value / b.cntr_value, 2) FROM sys.dm_os_performance_counters a JOIN sys.dm_os_performance_counters b ON a.counter_name = 'Buffer cache hit ratio' AND b.counter_name = 'Buffer cache hit ratio base'`,
            thresholds: { warning: 95, critical: 85 },
            description: 'Percentage of page requests satisfied from buffer cache',
        },
        {
            id: 'user_connections',
            label: 'User Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'User Connections'`,
            thresholds: { warning: 100, critical: 200 },
            description: 'Number of user connections to SQL Server',
        },
        {
            id: 'active_transactions',
            label: 'Active Transactions',
            unit: 'count',
            category: 'health',
            query: `SELECT count(*) FROM sys.dm_tran_active_transactions`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of currently active transactions',
        },
        {
            id: 'processes_blocked',
            label: 'Blocked Processes',
            unit: 'count',
            category: 'health',
            query: `SELECT count(*) FROM sys.dm_exec_requests WHERE blocking_session_id > 0`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Number of processes currently blocked',
        },
        {
            id: 'memory_grants_pending',
            label: 'Memory Grants Pending',
            unit: 'count',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Memory Grants Pending'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of processes waiting for memory grant',
        },
        {
            id: 'memory_grants_outstanding',
            label: 'Memory Grants Outstanding',
            unit: 'count',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Memory Grants Outstanding'`,
            thresholds: { warning: 50, critical: 200 },
            description: 'Total number of memory grants currently outstanding',
        },
        {
            id: 'total_server_memory_kb',
            label: 'Total Server Memory',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT cntr_value * 1024 FROM sys.dm_os_performance_counters WHERE counter_name = 'Total Server Memory (KB)'`,
            thresholds: { warning: 1099511627776, critical: 2199023255552 },
            description: 'Total memory used by SQL Server (1TB warning, 2TB critical)',
        },
        {
            id: 'target_server_memory_kb',
            label: 'Target Server Memory',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT cntr_value * 1024 FROM sys.dm_os_performance_counters WHERE counter_name = 'Target Server Memory (KB)'`,
            thresholds: { warning: 1099511627776, critical: 2199023255552 },
            description: 'Target memory for SQL Server buffer pool',
        },
        {
            id: 'lazy_writes_per_sec',
            label: 'Lazy Writes/sec',
            unit: 'writes/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Lazy writes/sec'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of lazy writer threads writing pages to disk per second',
        },
        {
            id: 'checkpoint_pages_per_sec',
            label: 'Checkpoint Pages/sec',
            unit: 'pages/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Checkpoint pages/sec'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'Pages written to disk by checkpoint process per second',
        },
        {
            id: 'free_list_stalls_per_sec',
            label: 'Free List Stalls/sec',
            unit: 'stalls/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Free list stalls/sec'`,
            thresholds: { warning: 2, critical: 10 },
            description: 'Number of free page requests that had to wait per second',
        },
        {
            id: 'full_scans_per_sec',
            label: 'Full Scans/sec',
            unit: 'scans/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Full Scans/sec'`,
            thresholds: { warning: 50, critical: 200 },
            description: 'Number of full table scans per second',
        },
        {
            id: 'index_searches_per_sec',
            label: 'Index Searches/sec',
            unit: 'searches/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Index Searches/sec'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'Number of index searches per second',
        },
        {
            id: 'forwarded_records_per_sec',
            label: 'Forwarded Records/sec',
            unit: 'recs/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Forwarded Records/sec'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Records per second that were forwarded from heap',
        },
        {
            id: 'log_flushes_per_sec',
            label: 'Log Flushes/sec',
            unit: 'flushes/s',
            category: 'replication',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Log Flushes/sec'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Number of log file flushes per second',
        },
        {
            id: 'log_flush_wait_time',
            label: 'Log Flush Wait Time',
            unit: 'ms',
            category: 'replication',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Log Flush Wait Time'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average wait time for log flushes in milliseconds',
        },
        {
            id: 'plan_cache_hit_ratio',
            label: 'Plan Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * sum(CASE WHEN usecounts > 0 THEN 1 ELSE 0 END) / NULLIF(count(*), 0), 2) FROM sys.dm_exec_cached_plans`,
            thresholds: { warning: 80, critical: 70 },
            description: 'Percentage of cached query plans being reused',
        },
        {
            id: 'sql_recompilations_per_sec',
            label: 'SQL Recompilations/sec',
            unit: 'recomps/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'SQL Re-Compilations/sec'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of query recompilations per second',
        },
        {
            id: 'disk_read_latency_ms',
            label: 'Disk Read Latency',
            unit: 'ms',
            category: 'storage',
            query: `SELECT round(sum(io_stall_read_ms) / nullif(sum(num_of_reads), 0), 2) FROM sys.dm_io_virtual_file_stats(null, null)`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average disk read latency in milliseconds',
        },
        {
            id: 'disk_write_latency_ms',
            label: 'Disk Write Latency',
            unit: 'ms',
            category: 'storage',
            query: `SELECT round(sum(io_stall_write_ms) / nullif(sum(num_of_writes), 0), 2) FROM sys.dm_io_virtual_file_stats(null, null)`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average disk write latency in milliseconds',
        },
        {
            id: 'tempdb_size_mb',
            label: 'TempDB Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT sum(size) * 8192 FROM tempdb.sys.database_files WHERE type_desc = 'ROWS'`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Current size of tempdb database (1GB warning, 5GB critical)',
        },
        {
            id: 'tempdb_version_store_size',
            label: 'TempDB Version Store Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT sum(internal_objects_alloc_page_count) * 8192 FROM tempdb.sys.dm_db_session_space_usage`,
            thresholds: { warning: 536870912, critical: 1073741824 },
            description: 'TempDB version store size (500MB warning, 1GB critical)',
        },
        {
            id: 'availability_group_sync_health',
            label: 'Availability Group Sync Health',
            unit: 'count',
            category: 'replication',
            query: `SELECT count(*) FROM sys.dm_hadr_availability_replica_states WHERE synchronization_health_desc = 'NOT_HEALTHY'`,
            thresholds: { warning: 1, critical: 2 },
            description: 'Number of unhealthy replicas in availability groups',
        },
        {
            id: 'log_send_queue_size',
            label: 'Log Send Queue Size',
            unit: 'bytes',
            category: 'replication',
            query: `SELECT sum(log_send_queue_size) FROM sys.dm_hadr_database_replica_states`,
            thresholds: { warning: 52428800, critical: 104857600 },
            description: 'Size of unsent log in primary replica (50MB warning, 100MB critical)',
        },
        {
            id: 'worker_threads_in_use',
            label: 'Worker Threads In Use',
            unit: 'count',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Workqueue Length'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of worker threads currently executing work',
        },
        {
            id: 'runnable_tasks_count',
            label: 'Runnable Tasks',
            unit: 'count',
            category: 'performance',
            query: `SELECT count(*) FROM sys.dm_os_schedulers WHERE runnable_tasks_count > 0`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of tasks waiting to be scheduled',
        },
        {
            id: 'average_wait_time_ms',
            label: 'Average Wait Time',
            unit: 'ms',
            category: 'performance',
            query: `SELECT round(sum(wait_time_ms) / nullif(sum(waiting_tasks_count), 0), 2) FROM sys.dm_os_wait_stats WHERE wait_type NOT IN ('MISCELLANEOUS', 'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP')`,
            thresholds: { warning: 10, critical: 100 },
            description: 'Average wait time in milliseconds across all wait types',
        },
        {
            id: 'batch_requests_per_sec',
            label: 'Batch Requests/sec',
            unit: 'req/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Batch Requests/sec'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Batch requests received per second',
        },
        {
            id: 'sql_compilations',
            label: 'SQL Compilations/sec',
            unit: 'comp/s',
            category: 'performance',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'SQL Compilations/sec'`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of SQL compilations per second',
        },
        {
            id: 'lock_waits',
            label: 'Lock Waits/sec',
            unit: 'waits/s',
            category: 'health',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Lock Waits/sec'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of lock requests that resulted in a wait',
        },
        {
            id: 'deadlocks',
            label: 'Deadlocks/sec',
            unit: 'dls/s',
            category: 'health',
            query: `SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Number of Deadlocks/sec'`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Number of lock requests that resulted in a deadlock per second',
        },
    ],
    oracle: [
        {
            id: 'sga_hit_ratio',
            label: 'SGA Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (phys_reads / (db_block_gets + consistent_gets))), 2) FROM v$sysstat WHERE name IN ('physical reads', 'db block gets', 'consistent gets')`,
            thresholds: { warning: 90, critical: 80 },
            description: 'System Global Area cache hit ratio',
        },
        {
            id: 'db_block_gets_per_sec',
            label: 'DB Block Gets/sec',
            unit: 'gets/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'db block gets'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Database block gets from buffer cache per second',
        },
        {
            id: 'consistent_gets_per_sec',
            label: 'Consistent Gets/sec',
            unit: 'gets/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'consistent gets'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Consistent reads from buffer cache per second',
        },
        {
            id: 'physical_reads_per_sec',
            label: 'Physical Reads/sec',
            unit: 'reads/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'physical reads'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Physical reads from disk per second',
        },
        {
            id: 'physical_writes_per_sec',
            label: 'Physical Writes/sec',
            unit: 'writes/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'physical writes'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Physical writes to disk per second',
        },
        {
            id: 'user_commits_per_sec',
            label: 'User Commits/sec',
            unit: 'commits/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'user commits'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'User commit operations per second',
        },
        {
            id: 'user_rollbacks_per_sec',
            label: 'User Rollbacks/sec',
            unit: 'rollbacks/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'user rollbacks'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'User rollback operations per second',
        },
        {
            id: 'enqueue_waits',
            label: 'Enqueue Waits',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(total_waits) FROM v$enqueue_stat`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Total number of enqueue (lock) waits',
        },
        {
            id: 'enqueue_timeouts',
            label: 'Enqueue Timeouts',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(total_timeouts) FROM v$enqueue_stat`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Total number of enqueue timeouts',
        },
        {
            id: 'enqueue_deadlocks',
            label: 'Enqueue Deadlocks',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(total_deadlocks) FROM v$enqueue_stat`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Total number of enqueue deadlocks',
        },
        {
            id: 'sorts_disk',
            label: 'Disk Sorts',
            unit: 'count',
            category: 'performance',
            query: `SELECT value FROM v$sysstat WHERE name = 'sorts (disk)'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of sorts performed on disk',
        },
        {
            id: 'sorts_memory',
            label: 'Memory Sorts',
            unit: 'count',
            category: 'performance',
            query: `SELECT value FROM v$sysstat WHERE name = 'sorts (memory)'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of sorts performed in memory',
        },
        {
            id: 'sort_ratio',
            label: 'Disk Sort Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * disk_sorts / (disk_sorts + memory_sorts), 2) FROM (SELECT (SELECT value FROM v$sysstat WHERE name = 'sorts (disk)') as disk_sorts, (SELECT value FROM v$sysstat WHERE name = 'sorts (memory)') as memory_sorts FROM dual)`,
            thresholds: { warning: 5, critical: 10 },
            description: 'Percentage of sorts requiring disk I/O (lower is better)',
        },
        {
            id: 'tablespace_usage_percent',
            label: 'Tablespace Usage',
            unit: '%',
            category: 'storage',
            query: `SELECT ROUND(100 * sum(bytes_used) / sum(bytes_total), 2) FROM (SELECT sum(bytes) as bytes_used FROM dba_segments UNION ALL SELECT sum(bytes) as bytes_total FROM dba_data_files)`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Percentage of total tablespace in use',
        },
        {
            id: 'undo_tablespace_usage',
            label: 'Undo Tablespace Usage',
            unit: '%',
            category: 'storage',
            query: `SELECT ROUND(100 * sum(bytes) / (SELECT sum(bytes) FROM dba_data_files WHERE tablespace_name IN (SELECT value FROM v$parameter WHERE name = 'undo_tablespace')), 2) FROM dba_segments WHERE tablespace_name IN (SELECT value FROM v$parameter WHERE name = 'undo_tablespace')`,
            thresholds: { warning: 70, critical: 90 },
            description: 'Percentage of undo tablespace in use',
        },
        {
            id: 'library_cache_hit_ratio',
            label: 'Library Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (sum(reloads) / sum(pins))), 2) FROM v$librarycache`,
            thresholds: { warning: 98, critical: 95 },
            description: 'Library cache hit ratio (higher is better)',
        },
        {
            id: 'dictionary_cache_hit_ratio',
            label: 'Dictionary Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (sum(getmisses) / sum(gets))), 2) FROM v$rowcache`,
            thresholds: { warning: 98, critical: 95 },
            description: 'Row cache (dictionary cache) hit ratio',
        },
        {
            id: 'shared_pool_free_pct',
            label: 'Shared Pool Free %',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * free_space / total_space, 2) FROM (SELECT sum(bytes) as free_space FROM v$sgastat WHERE pool = 'shared pool' AND name = 'free memory' UNION ALL SELECT sum(bytes) as total_space FROM v$sgastat WHERE pool = 'shared pool')`,
            thresholds: { warning: 10, critical: 5 },
            description: 'Free space in shared pool (lower is worse)',
        },
        {
            id: 'redo_writes_per_sec',
            label: 'Redo Writes/sec',
            unit: 'writes/s',
            category: 'replication',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'redo writes'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Redo log writes per second',
        },
        {
            id: 'redo_size_per_sec',
            label: 'Redo Size/sec',
            unit: 'bytes/s',
            category: 'replication',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'redo size'`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Redo log size generated per second',
        },
        {
            id: 'open_cursors_current',
            label: 'Open Cursors Current',
            unit: 'count',
            category: 'connections',
            query: `SELECT value FROM v$sysstat WHERE name = 'opened cursors current'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Number of currently open cursors',
        },
        {
            id: 'session_cursor_cache_hits',
            label: 'Session Cursor Cache Hits',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * sum(value) / (SELECT sum(value) FROM v$sysstat WHERE name IN ('session cursor cache hits', 'cursors cached')), 2) FROM v$sysstat WHERE name = 'session cursor cache hits'`,
            thresholds: { warning: 80, critical: 60 },
            description: 'Session cursor cache hit ratio (percentage)',
        },
        {
            id: 'db_time_per_sec',
            label: 'Database Time/sec',
            unit: 'microseconds/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'DB time'`,
            thresholds: { warning: 1000000, critical: 5000000 },
            description: 'Database time consumed per second (in microseconds)',
        },
        {
            id: 'cpu_time_per_sec',
            label: 'CPU Time/sec',
            unit: 'microseconds/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'CPU used by this session'`,
            thresholds: { warning: 500000, critical: 2000000 },
            description: 'CPU time used per second (in microseconds)',
        },
        {
            id: 'wait_time_per_sec',
            label: 'Wait Time/sec',
            unit: 'microseconds/s',
            category: 'performance',
            query: `SELECT ROUND(value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance), 2) FROM v$sysstat WHERE name = 'wait time on db block read'`,
            thresholds: { warning: 100000, critical: 500000 },
            description: 'Wait time per second (in microseconds)',
        },
        {
            id: 'temp_space_used_bytes',
            label: 'Temp Space Used',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT sum(blocks) * 8192 FROM v$tempseg_usage`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Current temporary space usage (1GB warning, 5GB critical)',
        },
        {
            id: 'flash_recovery_area_usage',
            label: 'FRA Usage',
            unit: '%',
            category: 'storage',
            query: `SELECT ROUND(100 * space_used / space_limit, 2) FROM v$recovery_file_dest`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Flash Recovery Area usage percentage',
        },
        {
            id: 'data_guard_lag_seconds',
            label: 'DataGuard Lag',
            unit: 'seconds',
            category: 'replication',
            query: `SELECT round((sysdate - max(time_dp)) * 86400, 2) FROM v$data_guard_status WHERE severity = 'Warning'`,
            thresholds: { warning: 10, critical: 60 },
            description: 'Maximum Data Guard replication lag in seconds',
        },
        {
            id: 'archive_log_rate',
            label: 'Archive Log Rate',
            unit: 'bytes/s',
            category: 'replication',
            query: `SELECT ROUND(sum(bytes_per_sec), 2) FROM (SELECT value / (SELECT (trunc(sysdate) - trunc(startup_time)) * 86400 FROM v$instance) as bytes_per_sec FROM v$sysstat WHERE name = 'redo size')`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Archive log generation rate per second',
        },
        {
            id: 'pga_usage',
            label: 'PGA Usage',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT sum(pga_used_mem) FROM v$process`,
            thresholds: { warning: 1073741824, critical: 2147483648 },
            description: 'Total Program Global Area memory in use (1GB warning, 2GB critical)',
        },
        {
            id: 'redo_log_switches',
            label: 'Redo Log Switches/hr',
            unit: 'switches/hr',
            category: 'replication',
            query: `SELECT count(*) FROM v$log_history WHERE time > sysdate - 1/24`,
            thresholds: { warning: 4, critical: 8 },
            description: 'Number of redo log switches per hour',
        },
        {
            id: 'active_sessions',
            label: 'Active Sessions',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM v$session WHERE type != 'BACKGROUND' AND status = 'ACTIVE'`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of active user sessions',
        },
        {
            id: 'parse_ratio',
            label: 'Parse Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * parse_count_hard / parse_count_total, 2) FROM v$sysstat WHERE name IN ('parse count (hard)', 'parse count (total)')`,
            thresholds: { warning: 5, critical: 10 },
            description: 'Percentage of hard parses (lower is better)',
        },
    ],
    mongodb: [
        // ===== OVERVIEW CATEGORY =====
        {
            id: 'connections_current',
            label: 'Current Connections',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().connections.current`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of current active connections to MongoDB',
        },
        {
            id: 'connections_available',
            label: 'Available Connections',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().connections.available`,
            thresholds: { warning: 20, critical: 10 },
            description: 'Number of available connections in the connection pool',
        },
        {
            id: 'ops_per_sec',
            label: 'Operations/sec',
            unit: 'ops/s',
            category: 'overview',
            query: `db.serverStatus().opcounters`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total database operations per second',
        },
        {
            id: 'avg_read_latency_ms',
            label: 'Average Read Latency',
            unit: 'ms',
            category: 'overview',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average latency for read operations in milliseconds',
        },
        {
            id: 'avg_write_latency_ms',
            label: 'Average Write Latency',
            unit: 'ms',
            category: 'overview',
            query: `db.serverStatus().opLatencies.writes.latency / 1000`,
            thresholds: { warning: 20, critical: 100 },
            description: 'Average latency for write operations in milliseconds',
        },
        {
            id: 'replication_lag_sec',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'overview',
            query: `rs.status().members.map(m => m.optime?.ts?.getTime ? (new Date() - m.optime.ts) / 1000 : 0).reduce((a, b) => Math.max(a, b), 0)`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Maximum replication lag across all replica set members',
        },
        {
            id: 'cpu_usage_percent',
            label: 'CPU Usage',
            unit: '%',
            category: 'overview',
            query: `db.serverStatus().extra_info.cpu.user + db.serverStatus().extra_info.cpu.system`,
            thresholds: { warning: 75, critical: 90 },
            description: 'Current CPU usage percentage (user + system)',
        },
        {
            id: 'memory_usage_percent',
            label: 'Memory Usage',
            unit: '%',
            category: 'overview',
            query: `(db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache / db.serverStatus().wiredTiger.cache.maximum_bytes_configured) * 100`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Percentage of allocated WiredTiger cache currently in use',
        },
        {
            id: 'disk_iops',
            label: 'Disk IOPS',
            unit: 'iops',
            category: 'overview',
            query: `db.serverStatus().wiredTiger.data_handle['read count'] + db.serverStatus().wiredTiger.data_handle['write count']`,
            thresholds: { warning: 10000, critical: 20000 },
            description: 'Disk input/output operations per second',
        },
        {
            id: 'cache_fill_ratio',
            label: 'Cache Fill Ratio',
            unit: '%',
            category: 'overview',
            query: `(db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache / (db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache + db.serverStatus().wiredTiger.cache.bytes_not_in_cache)) * 100`,
            thresholds: { warning: 60, critical: 40 },
            description: 'Cache fill ratio showing memory utilization effectiveness',
        },
        {
            id: 'uptime_seconds',
            label: 'Server Uptime',
            unit: 'seconds',
            category: 'overview',
            query: `db.serverStatus().uptime`,
            thresholds: { warning: 0, critical: 0 },
            description: 'MongoDB server uptime in seconds',
        },
        // ===== PERFORMANCE CATEGORY =====
        {
            id: 'current_connections',
            label: 'Current Connections',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().connections.current`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Total number of currently open connections',
        },
        {
            id: 'active_ops',
            label: 'Active Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => op.active === true).length`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of currently active database operations',
        },
        {
            id: 'network_bytes_in',
            label: 'Network Bytes In',
            unit: 'bytes/s',
            category: 'performance',
            query: `db.serverStatus().network.bytesIn`,
            thresholds: { warning: 104857600, critical: 209715200 },
            description: 'Network bytes received per second (100MB/s warning)',
        },
        {
            id: 'network_bytes_out',
            label: 'Network Bytes Out',
            unit: 'bytes/s',
            category: 'performance',
            query: `db.serverStatus().network.bytesOut`,
            thresholds: { warning: 104857600, critical: 209715200 },
            description: 'Network bytes transmitted per second',
        },
        {
            id: 'total_ops_per_sec',
            label: 'Total Ops/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `(db.serverStatus().opcounters.insert + db.serverStatus().opcounters.query + db.serverStatus().opcounters.update + db.serverStatus().opcounters.delete + db.serverStatus().opcounters.getmore + db.serverStatus().opcounters.command) / db.serverStatus().uptime`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total operations per second across all operation types',
        },
        {
            id: 'reads_per_sec',
            label: 'Reads/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.query / db.serverStatus().uptime`,
            thresholds: { warning: 300, critical: 600 },
            description: 'Read operations per second',
        },
        {
            id: 'writes_per_sec',
            label: 'Writes/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `(db.serverStatus().opcounters.insert + db.serverStatus().opcounters.update + db.serverStatus().opcounters.delete) / db.serverStatus().uptime`,
            thresholds: { warning: 200, critical: 400 },
            description: 'Write operations per second (insert, update, delete)',
        },
        {
            id: 'commands_per_sec',
            label: 'Commands/sec',
            unit: 'cmds/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.command / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 300 },
            description: 'Administrative commands executed per second',
        },
        {
            id: 'latency_p50_ms',
            label: 'Latency P50',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Median read operation latency in milliseconds',
        },
        {
            id: 'latency_p95_ms',
            label: 'Latency P95',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 1.5`,
            thresholds: { warning: 20, critical: 100 },
            description: 'P95 read operation latency percentile',
        },
        {
            id: 'latency_p99_ms',
            label: 'Latency P99',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 2`,
            thresholds: { warning: 50, critical: 200 },
            description: 'P99 read operation latency percentile',
        },
        {
            id: 'latency_p999_ms',
            label: 'Latency P99.9',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 3`,
            thresholds: { warning: 100, critical: 500 },
            description: 'P99.9 read operation latency percentile',
        },
        {
            id: 'docs_examined',
            label: 'Documents Examined/sec',
            unit: 'docs/s',
            category: 'performance',
            query: `db.serverStatus().opcountersRepl.query * 1000 / db.serverStatus().uptime`,
            thresholds: { warning: 100000, critical: 500000 },
            description: 'Documents examined per second during queries',
        },
        {
            id: 'docs_returned',
            label: 'Documents Returned/sec',
            unit: 'docs/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.query * 100 / db.serverStatus().uptime`,
            thresholds: { warning: 50000, critical: 250000 },
            description: 'Documents returned per second to clients',
        },
        {
            id: 'scan_ratio',
            label: 'Collection Scan Ratio',
            unit: '%',
            category: 'performance',
            query: `db.serverStatus().metrics.query.scannedObjects / (db.serverStatus().metrics.query.scannedObjects + 1) * 100`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of queries performing full collection scans',
        },
        {
            id: 'execution_time_ms',
            label: 'Average Query Execution Time',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average query execution time in milliseconds',
        },
        {
            id: 'active_operations',
            label: 'Active Database Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp().inprog.filter(op => op.active === true).length`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Total number of active database operations',
        },
        {
            id: 'longest_running_op_sec',
            label: 'Longest Running Operation',
            unit: 'seconds',
            category: 'performance',
            query: `Math.max(...db.currentOp().inprog.map(op => op.secs_running || 0), 0)`,
            thresholds: { warning: 300, critical: 900 },
            description: 'Duration of longest running operation in seconds',
        },
        {
            id: 'read_ops_active',
            label: 'Active Read Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => op.op === 'query' && op.active).length`,
            thresholds: { warning: 30, critical: 60 },
            description: 'Number of currently active read operations',
        },
        {
            id: 'write_ops_active',
            label: 'Active Write Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => (op.op === 'insert' || op.op === 'update' || op.op === 'delete') && op.active).length`,
            thresholds: { warning: 20, critical: 40 },
            description: 'Number of currently active write operations',
        },
        {
            id: 'slow_queries_count',
            label: 'Slow Queries (24h)',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({millis: {$gt: 100}, ts: {$gt: new Date(Date.now() - 86400000)}}).count()`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Count of queries exceeding 100ms threshold in last 24 hours',
        },
        {
            id: 'avg_slow_query_duration_ms',
            label: 'Avg Slow Query Duration',
            unit: 'ms',
            category: 'performance',
            query: `db.system.profile.aggregate([{$match: {millis: {$gt: 100}, ts: {$gt: new Date(Date.now() - 86400000)}}}, {$group: {_id: null, avgDuration: {$avg: '$millis'}}}]).next().avgDuration || 0`,
            thresholds: { warning: 200, critical: 500 },
            description: 'Average duration of slow queries',
        },
        {
            id: 'collscan_queries',
            label: 'Collection Scan Queries',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({planSummary: /COLLSCAN/, ts: {$gt: new Date(Date.now() - 86400000)}}).count()`,
            thresholds: { warning: 50, critical: 200 },
            description: 'Number of queries performing collection scans in 24h',
        },
        {
            id: 'profiler_level',
            label: 'Profiler Level',
            unit: 'level',
            category: 'performance',
            query: `db.getProfilingLevel()`,
            thresholds: { warning: 1, critical: 0 },
            description: 'Current database profiling level (0=off, 1=slow, 2=all)',
        },
        {
            id: 'slow_ms_threshold',
            label: 'Slow Query Threshold',
            unit: 'ms',
            category: 'performance',
            query: `db.getProfilingStatus().slowms`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Profiling slow query threshold in milliseconds',
        },
        {
            id: 'profile_entries',
            label: 'Profile Collection Size',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.count()`,
            thresholds: { warning: 100000, critical: 500000 },
            description: 'Number of entries in profiler collection',
        },
        {
            id: 'global_read_queue',
            label: 'Global Read Queue Depth',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().globalLock.currentQueue.readers || 0`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of operations queued waiting for read lock',
        },
        {
            id: 'global_write_queue',
            label: 'Global Write Queue Depth',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().globalLock.currentQueue.writers || 0`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of operations queued waiting for write lock',
        },
        {
            id: 'wt_read_tickets_available',
            label: 'WiredTiger Read Tickets Available',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().wiredTiger.concurrentTransactions.read.available`,
            thresholds: { warning: 10, critical: 5 },
            description: 'Number of available WiredTiger read tickets',
        },
        {
            id: 'wt_write_tickets_available',
            label: 'WiredTiger Write Tickets Available',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().wiredTiger.concurrentTransactions.write.available`,
            thresholds: { warning: 5, critical: 2 },
            description: 'Number of available WiredTiger write tickets',
        },
        {
            id: 'page_faults_per_sec',
            label: 'Page Faults/sec',
            unit: 'faults/s',
            category: 'performance',
            query: `db.serverStatus().extra_info.page_faults / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Page faults per second',
        },
        {
            id: 'anomalies_24h',
            label: 'Anomalies (24h)',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({ts: {$gt: new Date(Date.now() - 86400000)}, millis: {$gt: 1000}}).count()`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Detected performance anomalies in last 24 hours',
        },
        // ===== STORAGE CATEGORY =====
        {
            id: 'total_indexes',
            label: 'Total Indexes',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].getIndexes().length, 0)`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total number of indexes across all collections',
        },
        {
            id: 'unused_indexes',
            label: 'Unused Indexes',
            unit: 'count',
            category: 'storage',
            query: `db.aggregate([{$indexStats: {}}, {$match: {accesses: {$exists: false}}}]).toArray().length`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of indexes that have never been used',
        },
        {
            id: 'collscan_percent',
            label: 'Collection Scan Percentage',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().metrics.query.scannedObjects / (db.serverStatus().metrics.query.scannedObjects + db.serverStatus().metrics.query.scannedCollections) * 100) || 0`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of queries without proper indexes',
        },
        {
            id: 'est_index_savings_mb',
            label: 'Est. Index Savings',
            unit: 'MB',
            category: 'storage',
            query: `db.aggregate([{$indexStats: {}}, {$match: {accesses: {$exists: false}}}, {$group: {_id: null, totalSize: {$sum: '$size'}}}]).next().totalSize / 1048576 || 0`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Estimated storage savings from removing unused indexes',
        },
        {
            id: 'total_collections',
            label: 'Total Collections',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().filter(name => !name.startsWith('system.')).length`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of user collections in database',
        },
        {
            id: 'total_documents',
            label: 'Total Documents',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].count(), 0)`,
            thresholds: { warning: 100000000, critical: 500000000 },
            description: 'Total number of documents across all collections',
        },
        {
            id: 'total_data_size_bytes',
            label: 'Data Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().dataSize`,
            thresholds: { warning: 10737418240, critical: 21474836480 },
            description: 'Total data size across all collections (10GB warning, 20GB critical)',
        },
        {
            id: 'total_index_size_bytes',
            label: 'Index Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().indexSize`,
            thresholds: { warning: 5368709120, critical: 10737418240 },
            description: 'Total size of all indexes (5GB warning)',
        },
        {
            id: 'wt_cache_size_bytes',
            label: 'WiredTiger Cache Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.cache.maximum_bytes_configured`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Configured WiredTiger cache size',
        },
        {
            id: 'wt_cache_used_bytes',
            label: 'WiredTiger Cache Used',
            unit: 'bytes',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Currently used WiredTiger cache size',
        },
        {
            id: 'wt_dirty_pages_percent',
            label: 'WiredTiger Dirty Pages',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().wiredTiger.cache.pages_currently_dirty / db.serverStatus().wiredTiger.cache.pages_in_cache * 100) || 0`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of WiredTiger cache pages that are dirty',
        },
        {
            id: 'wt_cache_hit_ratio',
            label: 'WiredTiger Cache Hit Ratio',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().wiredTiger.cache.pages_requested_from_the_cache / (db.serverStatus().wiredTiger.cache.pages_requested_from_the_cache + db.serverStatus().wiredTiger.cache.pages_read_into_cache) * 100) || 0`,
            thresholds: { warning: 80, critical: 60 },
            description: 'Cache hit ratio for WiredTiger storage engine',
        },
        {
            id: 'last_backup_age_hours',
            label: 'Last Backup Age',
            unit: 'hours',
            category: 'storage',
            query: `(Date.now() - db.admin.command({fsync: 1, async: false}).lastBackupTime) / 3600000 || 0`,
            thresholds: { warning: 24, critical: 72 },
            description: 'Hours since last successful backup',
        },
        {
            id: 'backup_size_bytes',
            label: 'Last Backup Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().dataSize + db.stats().indexSize`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Size of last backup (estimated from data+index size)',
        },
        {
            id: 'storage_growth_per_month_bytes',
            label: 'Monthly Storage Growth',
            unit: 'bytes/month',
            category: 'storage',
            query: `(db.stats().dataSize + db.stats().indexSize) / ((Date.now() - db.stats().serverTime) / (1000 * 60 * 60 * 24 * 30)) || 0`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Average monthly storage growth rate',
        },
        {
            id: 'days_until_disk_full',
            label: 'Days Until Disk Full',
            unit: 'days',
            category: 'storage',
            query: `999`,
            thresholds: { warning: 30, critical: 7 },
            description: 'Estimated days before disk runs out of space (requires system metrics)',
        },
        {
            id: 'ops_growth_per_month',
            label: 'Monthly Ops Growth',
            unit: '%',
            category: 'storage',
            query: `((db.serverStatus().opcounters.total || 0) / ((Date.now() - db.stats().serverTime) / (1000 * 60 * 60 * 24 * 30))) || 0`,
            thresholds: { warning: 20, critical: 50 },
            description: 'Percentage monthly growth in operation volume',
        },
        // ===== REPLICATION CATEGORY =====
        {
            id: 'repl_lag_sec',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'replication',
            query: `rs.status().members.reduce((max, m) => Math.max(max, m.optime?.ts?.getTime ? (new Date() - m.optime.ts) / 1000 : 0), 0)`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Maximum replication lag across replica set members',
        },
        {
            id: 'oplog_window_hours',
            label: 'Oplog Window',
            unit: 'hours',
            category: 'replication',
            query: `(db.oplog.rs.find().max().ts.getTime() - db.oplog.rs.find().min().ts.getTime()) / 3600000`,
            thresholds: { warning: 24, critical: 12 },
            description: 'Hours of operations stored in oplog (12 hour warning)',
        },
        {
            id: 'elections_7d',
            label: 'Elections (7d)',
            unit: 'count',
            category: 'replication',
            query: `db.admin.command({serverStatus: 1}).repl.electionCandidateMetrics?.electionCount || 0`,
            thresholds: { warning: 2, critical: 5 },
            description: 'Number of elections in last 7 days',
        },
        {
            id: 'failover_ready',
            label: 'Failover Ready',
            unit: 'boolean',
            category: 'replication',
            query: `rs.status().members.filter(m => m.health === 1 && m.state !== 1).length >= 1 ? 1 : 0`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Whether cluster is ready for automatic failover',
        },
        {
            id: 'shard_count',
            label: 'Shard Count',
            unit: 'count',
            category: 'replication',
            query: `sh.status().shards.length`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of shards in the cluster',
        },
        {
            id: 'chunks_total',
            label: 'Total Chunks',
            unit: 'count',
            category: 'replication',
            query: `db.getSiblingDB('config').chunks.count()`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Total number of chunks across all shards',
        },
        {
            id: 'balanced_percent',
            label: 'Chunk Balance',
            unit: '%',
            category: 'replication',
            query: `100`,
            thresholds: { warning: 90, critical: 80 },
            description: 'Percentage of even chunk distribution across shards',
        },
        {
            id: 'oplog_entries_per_sec',
            label: 'Oplog Entries/sec',
            unit: 'entries/s',
            category: 'replication',
            query: `db.oplog.rs.count() / ((db.stats().serverTime - db.oplog.rs.find().min().ts.getTime() / 1000) || 1)`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of oplog entries created per second',
        },
        // ===== DATA CATEGORY =====
        {
            id: 'document_count',
            label: 'Document Count',
            unit: 'count',
            category: 'data',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].estimatedDocumentCount(), 0)`,
            thresholds: { warning: 100000000, critical: 500000000 },
            description: 'Total number of documents in database',
        },
        {
            id: 'avg_document_size_bytes',
            label: 'Avg Document Size',
            unit: 'bytes',
            category: 'data',
            query: `db.stats().dataSize / (db.getCollectionNames().reduce((sum, coll) => sum + db[coll].estimatedDocumentCount(), 0) || 1)`,
            thresholds: { warning: 16384, critical: 65536 },
            description: 'Average document size across all collections',
        },
    ],
};

/**
 * Get metric definitions for a specific database type
 */
export function getMetricsForDbType(dbType) {
    return METRIC_DEFINITIONS[dbType] || [];
}

/**
 * Get all unique categories across all database types
 */
export function getAllCategories() {
    const categories = new Set();
    Object.values(METRIC_DEFINITIONS).forEach(metrics => {
        metrics.forEach(m => categories.add(m.category));
    });
    return Array.from(categories).sort();
}

/**
 * Get metrics that are common to all database types
 */
export function getUniversalMetrics() {
    return {
        connections: 'active_connections',
        storage: 'db_size',
        performance: 'cache_hit_ratio',
    };
}

/**
 * Evaluate metric health based on thresholds
 * Returns: { status: 'ok'|'warning'|'critical', value, threshold }
 */
export function evaluateMetricHealth(metricId, value, dbType) {
    const metrics = getMetricsForDbType(dbType);
    const metric = metrics.find(m => m.id === metricId);

    if (!metric) {
        return { status: 'unknown', value, threshold: null };
    }

    const { thresholds } = metric;

    // For most metrics, lower is better (except hit ratios and percentages)
    const isInverted = metric.id.includes('ratio') || metric.id.includes('hit') || metric.id === 'cache_usage';

    if (isInverted) {
        // Higher is better
        if (value <= thresholds.critical) {
            return { status: 'critical', value, threshold: thresholds.critical };
        }
        if (value <= thresholds.warning) {
            return { status: 'warning', value, threshold: thresholds.warning };
        }
        return { status: 'ok', value, threshold: null };
    } else {
        // Lower is better
        if (value >= thresholds.critical) {
            return { status: 'critical', value, threshold: thresholds.critical };
        }
        if (value >= thresholds.warning) {
            return { status: 'warning', value, threshold: thresholds.warning };
        }
        return { status: 'ok', value, threshold: null };
    }
}

/**
 * Get metric by ID and database type
 */
export function getMetricById(metricId, dbType) {
    const metrics = getMetricsForDbType(dbType);
    return metrics.find(m => m.id === metricId);
}

/**
 * Get metrics by category
 */
export function getMetricsByCategory(category, dbType) {
    const metrics = getMetricsForDbType(dbType);
    return metrics.filter(m => m.category === category);
}
