// ═════════════════════════════════════════════════════════════════════════════
// METRICS REGISTRY SERVICE — Dynamic metrics definitions by database type
// ═════════════════════════════════════════════════════════════════════════════

const METRIC_DEFINITIONS = {
    postgresql: [
        {
            id: 'cache_hit_ratio',
            label: 'Cache Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * sum(heap_blks_hit) / NULLIF(sum(heap_blks_hit + heap_blks_read), 0), 2) FROM pg_statio_user_tables`,
            thresholds: { warning: 90, critical: 80 },
            description: 'Percentage of heap blocks served from cache vs disk',
        },
        {
            id: 'active_connections',
            label: 'Active Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity WHERE state = 'active'`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of actively executing connections',
        },
        {
            id: 'transactions_per_sec',
            label: 'TPS',
            unit: 'tx/s',
            category: 'performance',
            query: `SELECT ROUND((sum(xact_commit) + sum(xact_rollback)) / EXTRACT(EPOCH FROM (now() - stats_reset)), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Transactions committed and rolled back per second',
        },
        {
            id: 'deadlock_count',
            label: 'Deadlocks',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(deadlocks) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Total number of deadlocks detected',
        },
        {
            id: 'replication_lag',
            label: 'Replication Lag',
            unit: 'bytes',
            category: 'replication',
            query: `SELECT COALESCE(MAX(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)), 0) FROM pg_replication_slots`,
            thresholds: { warning: 52428800, critical: 104857600 },
            description: 'WAL bytes behind on replica (50MB warning, 100MB critical)',
        },
        {
            id: 'dead_tuples_ratio',
            label: 'Dead Tuple Ratio',
            unit: '%',
            category: 'maintenance',
            query: `SELECT ROUND(100.0 * sum(n_dead_tup) / NULLIF(sum(n_live_tup + n_dead_tup), 0), 2) FROM pg_stat_user_tables`,
            thresholds: { warning: 10, critical: 20 },
            description: 'Percentage of dead tuples across all tables',
        },
        {
            id: 'db_size',
            label: 'Database Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT pg_database_size(current_database())`,
            thresholds: { warning: 10737418240, critical: 21474836480 },
            description: 'Total size of the current database (10GB warning, 20GB critical)',
        },
        {
            id: 'index_hit_ratio',
            label: 'Index Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100.0 * sum(idx_blks_hit) / NULLIF(sum(idx_blks_hit + idx_blks_read), 0), 2) FROM pg_statio_user_indexes`,
            thresholds: { warning: 95, critical: 85 },
            description: 'Percentage of index blocks served from cache',
        },
        {
            id: 'longest_transaction',
            label: 'Longest Transaction',
            unit: 'seconds',
            category: 'health',
            query: `SELECT EXTRACT(EPOCH FROM max(NOW() - xact_start)) FROM pg_stat_activity WHERE xact_start IS NOT NULL`,
            thresholds: { warning: 300, critical: 900 },
            description: 'Duration of longest running transaction (5min warning, 15min critical)',
        },
        {
            id: 'wal_generation_rate',
            label: 'WAL Generation',
            unit: 'bytes/s',
            category: 'replication',
            query: `SELECT ROUND(pg_wal_lsn_diff(pg_current_wal_lsn(), '0/0') / EXTRACT(EPOCH FROM (now() - pg_postmaster_start_time())), 2)`,
            thresholds: { warning: 10485760, critical: 20971520 },
            description: 'WAL generation rate (10MB/s warning, 20MB/s critical)',
        },
        {
            id: 'temp_files_size',
            label: 'Temp Files',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT COALESCE(sum(temp_files), 0) FROM pg_stat_statements WHERE temp_files > 0`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Total size of temporary files created (1GB warning, 5GB critical)',
        },
        {
            id: 'vacuum_running',
            label: 'Active Vacuums',
            unit: 'count',
            category: 'maintenance',
            query: `SELECT count(*) FROM pg_stat_activity WHERE query ILIKE '%VACUUM%'`,
            thresholds: { warning: 2, critical: 4 },
            description: 'Number of active VACUUM operations',
        },
        // ===== CHECKPOINT & BGWRITER =====
        {
            id: 'checkpoints_timed',
            label: 'Checkpoints Timed',
            unit: 'count',
            category: 'performance',
            query: `SELECT checkpoints_timed FROM pg_stat_bgwriter`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of scheduled checkpoints performed',
        },
        {
            id: 'checkpoints_req',
            label: 'Checkpoints Requested',
            unit: 'count',
            category: 'performance',
            query: `SELECT checkpoints_req FROM pg_stat_bgwriter`,
            thresholds: { warning: 10, critical: 30 },
            description: 'Number of requested checkpoints (high values indicate heavy writes)',
        },
        {
            id: 'checkpoint_write_time',
            label: 'Checkpoint Write Time',
            unit: 'ms',
            category: 'performance',
            query: `SELECT checkpoint_write_time FROM pg_stat_bgwriter`,
            thresholds: { warning: 30000, critical: 60000 },
            description: 'Time spent writing files during checkpoint (30s warning)',
        },
        {
            id: 'checkpoint_sync_time',
            label: 'Checkpoint Sync Time',
            unit: 'ms',
            category: 'performance',
            query: `SELECT checkpoint_sync_time FROM pg_stat_bgwriter`,
            thresholds: { warning: 10000, critical: 30000 },
            description: 'Time spent syncing files to disk during checkpoint',
        },
        {
            id: 'bgwriter_buffers_checkpoint',
            label: 'Buffers Written (Checkpoint)',
            unit: 'count',
            category: 'performance',
            query: `SELECT buffers_checkpoint FROM pg_stat_bgwriter`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of buffers written during checkpoints',
        },
        {
            id: 'bgwriter_buffers_clean',
            label: 'Buffers Written (BGWriter)',
            unit: 'count',
            category: 'performance',
            query: `SELECT buffers_clean FROM pg_stat_bgwriter`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of buffers written by background writer',
        },
        {
            id: 'bgwriter_maxwritten_clean',
            label: 'BGWriter Max Written Stops',
            unit: 'count',
            category: 'health',
            query: `SELECT maxwritten_clean FROM pg_stat_bgwriter`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Times bgwriter stopped because it had written too many buffers',
        },
        {
            id: 'buffers_backend',
            label: 'Buffers Written (Backend)',
            unit: 'count',
            category: 'performance',
            query: `SELECT buffers_backend FROM pg_stat_bgwriter`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Buffers written directly by backends (high = bgwriter too slow)',
        },
        {
            id: 'buffers_backend_fsync',
            label: 'Backend Fsyncs',
            unit: 'count',
            category: 'health',
            query: `SELECT buffers_backend_fsync FROM pg_stat_bgwriter`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Number of backend fsync calls (should be zero)',
        },
        // ===== CONNECTIONS (EXTENDED) =====
        {
            id: 'total_connections',
            label: 'Total Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity`,
            thresholds: { warning: 100, critical: 150 },
            description: 'Total number of connections including idle',
        },
        {
            id: 'idle_connections',
            label: 'Idle Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity WHERE state = 'idle'`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of connections in idle state',
        },
        {
            id: 'idle_in_transaction',
            label: 'Idle in Transaction',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity WHERE state = 'idle in transaction'`,
            thresholds: { warning: 5, critical: 15 },
            description: 'Connections idle inside open transactions (resource leaks)',
        },
        {
            id: 'waiting_connections',
            label: 'Waiting Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT count(*) FROM pg_stat_activity WHERE wait_event IS NOT NULL AND state = 'active'`,
            thresholds: { warning: 5, critical: 15 },
            description: 'Number of active connections waiting on locks or I/O',
        },
        {
            id: 'connection_utilization_pct',
            label: 'Connection Utilization',
            unit: '%',
            category: 'connections',
            query: `SELECT ROUND(100.0 * count(*) / current_setting('max_connections')::int, 2) FROM pg_stat_activity`,
            thresholds: { warning: 70, critical: 90 },
            description: 'Percentage of max_connections currently used',
        },
        // ===== TUPLE OPERATIONS =====
        {
            id: 'tuples_inserted_per_sec',
            label: 'Tuples Inserted/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(sum(tup_inserted) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of tuples inserted per second',
        },
        {
            id: 'tuples_updated_per_sec',
            label: 'Tuples Updated/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(sum(tup_updated) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'Number of tuples updated per second',
        },
        {
            id: 'tuples_deleted_per_sec',
            label: 'Tuples Deleted/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(sum(tup_deleted) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 200, critical: 1000 },
            description: 'Number of tuples deleted per second',
        },
        {
            id: 'tuples_fetched_per_sec',
            label: 'Tuples Fetched/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(sum(tup_fetched) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 5000, critical: 20000 },
            description: 'Number of tuples fetched per second',
        },
        {
            id: 'tuples_returned_per_sec',
            label: 'Tuples Returned/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(sum(tup_returned) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 10000, critical: 50000 },
            description: 'Number of tuples returned from scans per second',
        },
        // ===== LOCKS & BLOCKING =====
        {
            id: 'lock_count',
            label: 'Total Locks Held',
            unit: 'count',
            category: 'health',
            query: `SELECT count(*) FROM pg_locks WHERE granted = true`,
            thresholds: { warning: 100, critical: 300 },
            description: 'Number of locks currently held',
        },
        {
            id: 'blocked_queries',
            label: 'Blocked Queries',
            unit: 'count',
            category: 'health',
            query: `SELECT count(*) FROM pg_locks WHERE granted = false`,
            thresholds: { warning: 3, critical: 10 },
            description: 'Number of queries waiting to acquire a lock',
        },
        {
            id: 'exclusive_locks',
            label: 'Exclusive Locks',
            unit: 'count',
            category: 'health',
            query: `SELECT count(*) FROM pg_locks WHERE mode LIKE '%Exclusive%' AND granted = true`,
            thresholds: { warning: 10, critical: 30 },
            description: 'Number of exclusive locks currently held',
        },
        // ===== SCANS & QUERY PERFORMANCE =====
        {
            id: 'seq_scan_count',
            label: 'Sequential Scans',
            unit: 'count',
            category: 'performance',
            query: `SELECT sum(seq_scan) FROM pg_stat_user_tables`,
            thresholds: { warning: 10000, critical: 50000 },
            description: 'Total sequential scans across all user tables',
        },
        {
            id: 'idx_scan_count',
            label: 'Index Scans',
            unit: 'count',
            category: 'performance',
            query: `SELECT sum(idx_scan) FROM pg_stat_user_tables`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total index scans across all user tables',
        },
        {
            id: 'seq_to_idx_scan_ratio',
            label: 'Seq/Idx Scan Ratio',
            unit: 'ratio',
            category: 'performance',
            query: `SELECT ROUND(COALESCE(sum(seq_scan)::numeric / NULLIF(sum(idx_scan), 0), 0), 4) FROM pg_stat_user_tables`,
            thresholds: { warning: 0.5, critical: 1.0 },
            description: 'Ratio of sequential to index scans (lower is better)',
        },
        {
            id: 'commit_ratio',
            label: 'Commit Ratio',
            unit: '%',
            category: 'health',
            query: `SELECT ROUND(100.0 * sum(xact_commit) / NULLIF(sum(xact_commit + xact_rollback), 0), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 95, critical: 90 },
            description: 'Percentage of transactions that commit vs rollback',
        },
        {
            id: 'rollbacks',
            label: 'Rollbacks',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(xact_rollback) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Total number of transaction rollbacks',
        },
        // ===== STORAGE (EXTENDED) =====
        {
            id: 'tablespace_size',
            label: 'Tablespace Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT sum(pg_tablespace_size(oid)) FROM pg_tablespace`,
            thresholds: { warning: 21474836480, critical: 53687091200 },
            description: 'Total size of all tablespaces (20GB warning, 50GB critical)',
        },
        {
            id: 'table_count',
            label: 'Table Count',
            unit: 'count',
            category: 'storage',
            query: `SELECT count(*) FROM pg_stat_user_tables`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'Number of user tables in current database',
        },
        {
            id: 'index_count',
            label: 'Index Count',
            unit: 'count',
            category: 'storage',
            query: `SELECT count(*) FROM pg_stat_user_indexes`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of user indexes in current database',
        },
        {
            id: 'total_index_size',
            label: 'Total Index Size',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT sum(pg_indexes_size(relid)) FROM pg_stat_user_tables`,
            thresholds: { warning: 5368709120, critical: 10737418240 },
            description: 'Total size of all indexes (5GB warning)',
        },
        {
            id: 'bloat_ratio',
            label: 'Table Bloat Ratio',
            unit: '%',
            category: 'maintenance',
            query: `SELECT ROUND(100.0 * COALESCE(sum(n_dead_tup), 0) / NULLIF(sum(n_live_tup), 0), 2) FROM pg_stat_user_tables`,
            thresholds: { warning: 20, critical: 50 },
            description: 'Estimated table bloat percentage from dead tuples',
        },
        {
            id: 'unused_indexes',
            label: 'Unused Indexes',
            unit: 'count',
            category: 'maintenance',
            query: `SELECT count(*) FROM pg_stat_user_indexes WHERE idx_scan = 0 AND idx_tup_read = 0`,
            thresholds: { warning: 10, critical: 30 },
            description: 'Number of indexes with zero scans (candidates for removal)',
        },
        // ===== WAL & REPLICATION (EXTENDED) =====
        {
            id: 'wal_archive_success',
            label: 'WAL Archive Success',
            unit: 'count',
            category: 'replication',
            query: `SELECT archived_count FROM pg_stat_archiver`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of WAL files successfully archived',
        },
        {
            id: 'wal_archive_fail',
            label: 'WAL Archive Failures',
            unit: 'count',
            category: 'replication',
            query: `SELECT failed_count FROM pg_stat_archiver`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Number of WAL archive failures',
        },
        {
            id: 'replication_slots',
            label: 'Replication Slots',
            unit: 'count',
            category: 'replication',
            query: `SELECT count(*) FROM pg_replication_slots`,
            thresholds: { warning: 5, critical: 10 },
            description: 'Number of active replication slots',
        },
        {
            id: 'streaming_replicas',
            label: 'Streaming Replicas',
            unit: 'count',
            category: 'replication',
            query: `SELECT count(*) FROM pg_stat_replication WHERE state = 'streaming'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of streaming replication connections',
        },
        // ===== MAINTENANCE (EXTENDED) =====
        {
            id: 'autovacuum_count',
            label: 'Autovacuum Workers',
            unit: 'count',
            category: 'maintenance',
            query: `SELECT count(*) FROM pg_stat_activity WHERE query ILIKE '%autovacuum%'`,
            thresholds: { warning: 3, critical: 5 },
            description: 'Number of active autovacuum worker processes',
        },
        {
            id: 'last_vacuum_age_hours',
            label: 'Oldest Vacuum Age',
            unit: 'hours',
            category: 'maintenance',
            query: `SELECT ROUND(EXTRACT(EPOCH FROM (now() - min(COALESCE(last_autovacuum, last_vacuum)))) / 3600, 2) FROM pg_stat_user_tables WHERE COALESCE(last_autovacuum, last_vacuum) IS NOT NULL`,
            thresholds: { warning: 168, critical: 336 },
            description: 'Hours since oldest table was vacuumed (1 week warning)',
        },
        {
            id: 'last_analyze_age_hours',
            label: 'Oldest Analyze Age',
            unit: 'hours',
            category: 'maintenance',
            query: `SELECT ROUND(EXTRACT(EPOCH FROM (now() - min(COALESCE(last_autoanalyze, last_analyze)))) / 3600, 2) FROM pg_stat_user_tables WHERE COALESCE(last_autoanalyze, last_analyze) IS NOT NULL`,
            thresholds: { warning: 168, critical: 336 },
            description: 'Hours since oldest table was analyzed (1 week warning)',
        },
        {
            id: 'tables_needing_vacuum',
            label: 'Tables Needing Vacuum',
            unit: 'count',
            category: 'maintenance',
            query: `SELECT count(*) FROM pg_stat_user_tables WHERE n_dead_tup > 1000 AND n_dead_tup > 0.05 * n_live_tup`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Tables with significant dead tuples needing vacuum',
        },
        // ===== DISK I/O =====
        {
            id: 'blocks_read_per_sec',
            label: 'Disk Blocks Read/sec',
            unit: 'blocks/s',
            category: 'performance',
            query: `SELECT ROUND(sum(blks_read) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Physical disk blocks read per second',
        },
        {
            id: 'blocks_hit_per_sec',
            label: 'Buffer Hits/sec',
            unit: 'hits/s',
            category: 'performance',
            query: `SELECT ROUND(sum(blks_hit) / EXTRACT(EPOCH FROM (now() - min(stats_reset))), 2) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Buffer cache hits per second (higher is better)',
        },
        {
            id: 'temp_bytes_written',
            label: 'Temp Bytes Written',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT COALESCE(sum(temp_bytes), 0) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Total temp data written to disk (1GB warning, 5GB critical)',
        },
        // ===== CONFLICTS & ERRORS =====
        {
            id: 'conflicts',
            label: 'Recovery Conflicts',
            unit: 'count',
            category: 'health',
            query: `SELECT sum(conflicts) FROM pg_stat_database WHERE datname = current_database()`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Queries cancelled due to recovery conflicts on standby',
        },
    ],
    mysql: [
        {
            id: 'innodb_buffer_hit_ratio',
            label: 'InnoDB Buffer Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_read_requests'))), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_reads'`,
            thresholds: { warning: 95, critical: 85 },
            description: 'Percentage of InnoDB buffer pool reads from cache',
        },
        {
            id: 'innodb_buffer_pool_utilization',
            label: 'InnoDB Buffer Pool Utilization',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (pool_size - free_buffers) / pool_size, 2) FROM information_schema.innodb_buffer_pool_stats`,
            thresholds: { warning: 85, critical: 95 },
            description: 'Percentage of InnoDB buffer pool currently in use',
        },
        {
            id: 'innodb_log_waits',
            label: 'InnoDB Log Waits',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_log_waits'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of waits due to InnoDB log buffer being full',
        },
        {
            id: 'innodb_deadlocks',
            label: 'InnoDB Deadlocks',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_deadlocks'`,
            thresholds: { warning: 1, critical: 5 },
            description: 'Total number of InnoDB deadlocks detected',
        },
        {
            id: 'innodb_data_reads',
            label: 'InnoDB Data Reads/sec',
            unit: 'reads/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_reads'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'InnoDB physical data reads per second',
        },
        {
            id: 'innodb_data_writes',
            label: 'InnoDB Data Writes/sec',
            unit: 'writes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_writes'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'InnoDB physical data writes per second',
        },
        {
            id: 'threads_running',
            label: 'Threads Running',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_running'`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of threads currently executing queries',
        },
        {
            id: 'threads_cached',
            label: 'Threads Cached',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_cached'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of cached threads ready to handle new connections',
        },
        {
            id: 'threads_connected',
            label: 'Threads Connected',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_connected'`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of open connections',
        },
        {
            id: 'max_used_connections',
            label: 'Max Used Connections',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Max_used_connections'`,
            thresholds: { warning: 100, critical: 150 },
            description: 'Maximum number of connections used at any time',
        },
        {
            id: 'aborted_connections',
            label: 'Aborted Connections',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Aborted_connects'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of connections aborted due to client not closing properly',
        },
        {
            id: 'aborted_clients',
            label: 'Aborted Clients',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Aborted_clients'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of connections aborted due to client dead or timeout',
        },
        {
            id: 'com_select',
            label: 'SELECT Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_select'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'SELECT statements executed per second',
        },
        {
            id: 'com_insert',
            label: 'INSERT Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_insert'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'INSERT statements executed per second',
        },
        {
            id: 'com_update',
            label: 'UPDATE Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_update'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'UPDATE statements executed per second',
        },
        {
            id: 'com_delete',
            label: 'DELETE Statements/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_delete'`,
            thresholds: { warning: 50, critical: 200 },
            description: 'DELETE statements executed per second',
        },
        {
            id: 'bytes_sent',
            label: 'Bytes Sent/sec',
            unit: 'bytes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Bytes_sent'`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Bytes sent to all clients per second',
        },
        {
            id: 'bytes_received',
            label: 'Bytes Received/sec',
            unit: 'bytes/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Bytes_received'`,
            thresholds: { warning: 10485760, critical: 52428800 },
            description: 'Bytes received from all clients per second',
        },
        {
            id: 'innodb_row_lock_time_avg',
            label: 'InnoDB Avg Row Lock Wait Time',
            unit: 'ms',
            category: 'health',
            query: `SELECT ROUND(VARIABLE_VALUE / NULLIF((SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_waits'), 0), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_time'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average time in milliseconds for InnoDB row lock waits',
        },
        {
            id: 'innodb_rows_read_per_sec',
            label: 'InnoDB Rows Read/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_read'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'InnoDB rows read per second',
        },
        {
            id: 'innodb_rows_inserted_per_sec',
            label: 'InnoDB Rows Inserted/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_inserted'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'InnoDB rows inserted per second',
        },
        {
            id: 'binary_log_space',
            label: 'Binary Log Space',
            unit: 'bytes',
            category: 'replication',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Binlog_cache_disk_use'`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Cumulative space used by binary logs (1GB warning, 5GB critical)',
        },
        {
            id: 'binlog_cache_disk_use',
            label: 'Binlog Cache Disk Use',
            unit: 'count',
            category: 'replication',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Binlog_cache_disk_use'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of transactions using disk cache for binary log',
        },
        {
            id: 'open_files',
            label: 'Open Files',
            unit: 'count',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Open_files'`,
            thresholds: { warning: 1000, critical: 2000 },
            description: 'Number of currently open files',
        },
        {
            id: 'open_tables',
            label: 'Open Tables',
            unit: 'count',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Open_tables'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Number of currently open tables',
        },
        {
            id: 'table_locks_waited',
            label: 'Table Locks Waited',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Table_locks_waited'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of table lock requests that required waits',
        },
        {
            id: 'handler_read_rnd_next',
            label: 'Full Table Scans/sec',
            unit: 'scans/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Handler_read_rnd_next'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of full table scans per second (indicator of inefficient queries)',
        },
        {
            id: 'key_buffer_hit_ratio',
            label: 'Key Buffer Hit Ratio',
            unit: '%',
            category: 'performance',
            query: `SELECT ROUND(100 * (1 - (VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Key_read_requests'))), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Key_reads'`,
            thresholds: { warning: 95, critical: 85 },
            description: 'MyISAM key buffer hit ratio (higher is better)',
        },
        {
            id: 'sort_merge_passes',
            label: 'Sort Merge Passes',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Sort_merge_passes'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of merge passes required by the sort algorithm',
        },
        {
            id: 'select_full_join',
            label: 'Full Joins Without Index',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Select_full_join'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of full joins performed without using indexes',
        },
        {
            id: 'slow_queries',
            label: 'Slow Queries',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Slow_queries'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of queries exceeding long_query_time',
        },
        {
            id: 'innodb_row_lock_waits',
            label: 'Row Lock Waits',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_row_lock_waits'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of InnoDB row lock waits',
        },
        {
            id: 'questions_per_sec',
            label: 'Queries/sec',
            unit: 'q/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Questions'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Questions (statements) per second',
        },
        {
            id: 'table_open_cache_misses',
            label: 'Table Open Cache Misses',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Table_open_cache_misses'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of table open cache misses',
        },
        {
            id: 'replication_lag_seconds',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'replication',
            query: `SHOW SLAVE STATUS`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Seconds behind master in replication',
        },
        {
            id: 'tmp_disk_tables',
            label: 'Temp Disk Tables',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Created_tmp_disk_tables'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Number of temporary tables created on disk',
        },
        // ===== ADDITIONAL CONNECTIONS =====
        {
            id: 'threads_created',
            label: 'Threads Created',
            unit: 'count',
            category: 'connections',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_created'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Total threads created (high value means thread_cache_size too low)',
        },
        {
            id: 'connection_errors_internal',
            label: 'Connection Errors (Internal)',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Connection_errors_internal'`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Connections rejected due to internal server errors',
        },
        {
            id: 'connection_errors_max',
            label: 'Connection Errors (Max)',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Connection_errors_max_connections'`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Connections rejected because max_connections was reached',
        },
        // ===== ADDITIONAL INNODB =====
        {
            id: 'innodb_buffer_pool_dirty_pages',
            label: 'InnoDB Dirty Pages',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_pages_dirty'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of dirty pages in InnoDB buffer pool',
        },
        {
            id: 'innodb_buffer_pool_pages_free',
            label: 'InnoDB Free Pages',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_buffer_pool_pages_free'`,
            thresholds: { warning: 100, critical: 10 },
            description: 'Number of free pages in InnoDB buffer pool',
        },
        {
            id: 'innodb_os_log_written',
            label: 'InnoDB Redo Log Written',
            unit: 'bytes',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_os_log_written'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total bytes written to InnoDB redo log',
        },
        {
            id: 'innodb_os_log_fsyncs',
            label: 'InnoDB Redo Log Fsyncs',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_os_log_fsyncs'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of fsyncs done to the InnoDB redo log files',
        },
        {
            id: 'innodb_history_list_length',
            label: 'InnoDB History List Length',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_history_list_length'`,
            thresholds: { warning: 1000, critical: 10000 },
            description: 'Length of InnoDB undo log (purge lag indicator)',
        },
        {
            id: 'innodb_rows_updated_per_sec',
            label: 'InnoDB Rows Updated/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_updated'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'InnoDB rows updated per second',
        },
        {
            id: 'innodb_rows_deleted_per_sec',
            label: 'InnoDB Rows Deleted/sec',
            unit: 'rows/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_rows_deleted'`,
            thresholds: { warning: 200, critical: 1000 },
            description: 'InnoDB rows deleted per second',
        },
        {
            id: 'innodb_data_pending_reads',
            label: 'InnoDB Pending Reads',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_pending_reads'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of pending InnoDB data reads',
        },
        {
            id: 'innodb_data_pending_writes',
            label: 'InnoDB Pending Writes',
            unit: 'count',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_pending_writes'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of pending InnoDB data writes',
        },
        // ===== ADDITIONAL QUERY & PERFORMANCE =====
        {
            id: 'created_tmp_tables',
            label: 'Temp Tables (Memory)',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Created_tmp_tables'`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of temporary tables created in memory',
        },
        {
            id: 'com_commit',
            label: 'Commits/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_commit'`,
            thresholds: { warning: 500, critical: 2000 },
            description: 'COMMIT statements executed per second',
        },
        {
            id: 'com_rollback',
            label: 'Rollbacks/sec',
            unit: 'stmts/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Com_rollback'`,
            thresholds: { warning: 5, critical: 20 },
            description: 'ROLLBACK statements executed per second',
        },
        {
            id: 'handler_read_first',
            label: 'Handler Read First/sec',
            unit: 'reads/s',
            category: 'performance',
            query: `SELECT ROUND(VARIABLE_VALUE / (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'), 2) FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Handler_read_first'`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Full index scan rate (reads first entry in index)',
        },
        {
            id: 'select_range_check',
            label: 'Select Range Check',
            unit: 'count',
            category: 'performance',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Select_range_check'`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Joins without indexes that check key ranges after each row',
        },
        // ===== ADDITIONAL STORAGE =====
        {
            id: 'innodb_data_read_bytes',
            label: 'InnoDB Total Data Read',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_read'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total data read by InnoDB since startup',
        },
        {
            id: 'innodb_data_written_bytes',
            label: 'InnoDB Total Data Written',
            unit: 'bytes',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Innodb_data_written'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total data written by InnoDB since startup',
        },
        {
            id: 'table_definition_cache',
            label: 'Table Definition Cache',
            unit: 'count',
            category: 'storage',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Open_table_definitions'`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Number of cached table definitions',
        },
        // ===== ADDITIONAL REPLICATION =====
        {
            id: 'binlog_stmt_cache_disk_use',
            label: 'Binlog Stmt Cache Disk Use',
            unit: 'count',
            category: 'replication',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Binlog_stmt_cache_disk_use'`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Non-transactional statements spilling binlog cache to disk',
        },
        {
            id: 'uptime',
            label: 'Server Uptime',
            unit: 'seconds',
            category: 'health',
            query: `SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime'`,
            thresholds: { warning: 0, critical: 0 },
            description: 'MySQL server uptime in seconds',
        },
    ],
    mongodb: [
        // ===== OVERVIEW CATEGORY =====
        {
            id: 'connections_current',
            label: 'Current Connections',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().connections.current`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Number of current active connections to MongoDB',
        },
        {
            id: 'connections_available',
            label: 'Available Connections',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().connections.available`,
            thresholds: { warning: 20, critical: 10 },
            description: 'Number of available connections in the connection pool',
        },
        {
            id: 'ops_per_sec',
            label: 'Operations/sec',
            unit: 'ops/s',
            category: 'overview',
            query: `db.serverStatus().opcounters`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total database operations per second',
        },
        {
            id: 'avg_read_latency_ms',
            label: 'Average Read Latency',
            unit: 'ms',
            category: 'overview',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average latency for read operations in milliseconds',
        },
        {
            id: 'avg_write_latency_ms',
            label: 'Average Write Latency',
            unit: 'ms',
            category: 'overview',
            query: `db.serverStatus().opLatencies.writes.latency / 1000`,
            thresholds: { warning: 20, critical: 100 },
            description: 'Average latency for write operations in milliseconds',
        },
        {
            id: 'replication_lag_sec',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'overview',
            query: `rs.status().members.map(m => m.optime?.ts?.getTime ? (new Date() - m.optime.ts) / 1000 : 0).reduce((a, b) => Math.max(a, b), 0)`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Maximum replication lag across all replica set members',
        },
        {
            id: 'cpu_usage_percent',
            label: 'CPU Usage',
            unit: '%',
            category: 'overview',
            query: `db.serverStatus().extra_info.cpu.user + db.serverStatus().extra_info.cpu.system`,
            thresholds: { warning: 75, critical: 90 },
            description: 'Current CPU usage percentage (user + system)',
        },
        {
            id: 'memory_usage_percent',
            label: 'Memory Usage',
            unit: '%',
            category: 'overview',
            query: `(db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache / db.serverStatus().wiredTiger.cache.maximum_bytes_configured) * 100`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Percentage of allocated WiredTiger cache currently in use',
        },
        {
            id: 'disk_iops',
            label: 'Disk IOPS',
            unit: 'iops',
            category: 'overview',
            query: `db.serverStatus().wiredTiger.data_handle['read count'] + db.serverStatus().wiredTiger.data_handle['write count']`,
            thresholds: { warning: 10000, critical: 20000 },
            description: 'Disk input/output operations per second',
        },
        {
            id: 'cache_fill_ratio',
            label: 'Cache Fill Ratio',
            unit: '%',
            category: 'overview',
            query: `(db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache / (db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache + db.serverStatus().wiredTiger.cache.bytes_not_in_cache)) * 100`,
            thresholds: { warning: 60, critical: 40 },
            description: 'Cache fill ratio showing memory utilization effectiveness',
        },
        {
            id: 'uptime_seconds',
            label: 'Server Uptime',
            unit: 'seconds',
            category: 'overview',
            query: `db.serverStatus().uptime`,
            thresholds: { warning: 0, critical: 0 },
            description: 'MongoDB server uptime in seconds',
        },
        // ===== PERFORMANCE CATEGORY =====
        {
            id: 'current_connections',
            label: 'Current Connections',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().connections.current`,
            thresholds: { warning: 80, critical: 95 },
            description: 'Total number of currently open connections',
        },
        {
            id: 'active_ops',
            label: 'Active Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => op.active === true).length`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of currently active database operations',
        },
        {
            id: 'network_bytes_in',
            label: 'Network Bytes In',
            unit: 'bytes/s',
            category: 'performance',
            query: `db.serverStatus().network.bytesIn`,
            thresholds: { warning: 104857600, critical: 209715200 },
            description: 'Network bytes received per second (100MB/s warning)',
        },
        {
            id: 'network_bytes_out',
            label: 'Network Bytes Out',
            unit: 'bytes/s',
            category: 'performance',
            query: `db.serverStatus().network.bytesOut`,
            thresholds: { warning: 104857600, critical: 209715200 },
            description: 'Network bytes transmitted per second',
        },
        {
            id: 'total_ops_per_sec',
            label: 'Total Ops/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `(db.serverStatus().opcounters.insert + db.serverStatus().opcounters.query + db.serverStatus().opcounters.update + db.serverStatus().opcounters.delete + db.serverStatus().opcounters.getmore + db.serverStatus().opcounters.command) / db.serverStatus().uptime`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total operations per second across all operation types',
        },
        {
            id: 'reads_per_sec',
            label: 'Reads/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.query / db.serverStatus().uptime`,
            thresholds: { warning: 300, critical: 600 },
            description: 'Read operations per second',
        },
        {
            id: 'writes_per_sec',
            label: 'Writes/sec',
            unit: 'ops/s',
            category: 'performance',
            query: `(db.serverStatus().opcounters.insert + db.serverStatus().opcounters.update + db.serverStatus().opcounters.delete) / db.serverStatus().uptime`,
            thresholds: { warning: 200, critical: 400 },
            description: 'Write operations per second (insert, update, delete)',
        },
        {
            id: 'commands_per_sec',
            label: 'Commands/sec',
            unit: 'cmds/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.command / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 300 },
            description: 'Administrative commands executed per second',
        },
        {
            id: 'latency_p50_ms',
            label: 'Latency P50',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Median read operation latency in milliseconds',
        },
        {
            id: 'latency_p95_ms',
            label: 'Latency P95',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 1.5`,
            thresholds: { warning: 20, critical: 100 },
            description: 'P95 read operation latency percentile',
        },
        {
            id: 'latency_p99_ms',
            label: 'Latency P99',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 2`,
            thresholds: { warning: 50, critical: 200 },
            description: 'P99 read operation latency percentile',
        },
        {
            id: 'latency_p999_ms',
            label: 'Latency P99.9',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000 * 3`,
            thresholds: { warning: 100, critical: 500 },
            description: 'P99.9 read operation latency percentile',
        },
        {
            id: 'docs_examined',
            label: 'Documents Examined/sec',
            unit: 'docs/s',
            category: 'performance',
            query: `db.serverStatus().opcountersRepl.query * 1000 / db.serverStatus().uptime`,
            thresholds: { warning: 100000, critical: 500000 },
            description: 'Documents examined per second during queries',
        },
        {
            id: 'docs_returned',
            label: 'Documents Returned/sec',
            unit: 'docs/s',
            category: 'performance',
            query: `db.serverStatus().opcounters.query * 100 / db.serverStatus().uptime`,
            thresholds: { warning: 50000, critical: 250000 },
            description: 'Documents returned per second to clients',
        },
        {
            id: 'scan_ratio',
            label: 'Collection Scan Ratio',
            unit: '%',
            category: 'performance',
            query: `db.serverStatus().metrics.query.scannedObjects / (db.serverStatus().metrics.query.scannedObjects + 1) * 100`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of queries performing full collection scans',
        },
        {
            id: 'execution_time_ms',
            label: 'Average Query Execution Time',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().opLatencies.reads.latency / 1000`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Average query execution time in milliseconds',
        },
        {
            id: 'active_operations',
            label: 'Active Database Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp().inprog.filter(op => op.active === true).length`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Total number of active database operations',
        },
        {
            id: 'longest_running_op_sec',
            label: 'Longest Running Operation',
            unit: 'seconds',
            category: 'performance',
            query: `Math.max(...db.currentOp().inprog.map(op => op.secs_running || 0), 0)`,
            thresholds: { warning: 300, critical: 900 },
            description: 'Duration of longest running operation in seconds',
        },
        {
            id: 'read_ops_active',
            label: 'Active Read Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => op.op === 'query' && op.active).length`,
            thresholds: { warning: 30, critical: 60 },
            description: 'Number of currently active read operations',
        },
        {
            id: 'write_ops_active',
            label: 'Active Write Operations',
            unit: 'count',
            category: 'performance',
            query: `db.currentOp(true).inprog.filter(op => (op.op === 'insert' || op.op === 'update' || op.op === 'delete') && op.active).length`,
            thresholds: { warning: 20, critical: 40 },
            description: 'Number of currently active write operations',
        },
        {
            id: 'slow_queries_count',
            label: 'Slow Queries (24h)',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({millis: {$gt: 100}, ts: {$gt: new Date(Date.now() - 86400000)}}).count()`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Count of queries exceeding 100ms threshold in last 24 hours',
        },
        {
            id: 'avg_slow_query_duration_ms',
            label: 'Avg Slow Query Duration',
            unit: 'ms',
            category: 'performance',
            query: `db.system.profile.aggregate([{$match: {millis: {$gt: 100}, ts: {$gt: new Date(Date.now() - 86400000)}}}, {$group: {_id: null, avgDuration: {$avg: '$millis'}}}]).next().avgDuration || 0`,
            thresholds: { warning: 200, critical: 500 },
            description: 'Average duration of slow queries',
        },
        {
            id: 'collscan_queries',
            label: 'Collection Scan Queries',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({planSummary: /COLLSCAN/, ts: {$gt: new Date(Date.now() - 86400000)}}).count()`,
            thresholds: { warning: 50, critical: 200 },
            description: 'Number of queries performing collection scans in 24h',
        },
        {
            id: 'profiler_level',
            label: 'Profiler Level',
            unit: 'level',
            category: 'performance',
            query: `db.getProfilingLevel()`,
            thresholds: { warning: 1, critical: 0 },
            description: 'Current database profiling level (0=off, 1=slow, 2=all)',
        },
        {
            id: 'slow_ms_threshold',
            label: 'Slow Query Threshold',
            unit: 'ms',
            category: 'performance',
            query: `db.getProfilingStatus().slowms`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Profiling slow query threshold in milliseconds',
        },
        {
            id: 'profile_entries',
            label: 'Profile Collection Size',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.count()`,
            thresholds: { warning: 100000, critical: 500000 },
            description: 'Number of entries in profiler collection',
        },
        {
            id: 'global_read_queue',
            label: 'Global Read Queue Depth',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().globalLock.currentQueue.readers || 0`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of operations queued waiting for read lock',
        },
        {
            id: 'global_write_queue',
            label: 'Global Write Queue Depth',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().globalLock.currentQueue.writers || 0`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of operations queued waiting for write lock',
        },
        {
            id: 'wt_read_tickets_available',
            label: 'WiredTiger Read Tickets Available',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().wiredTiger.concurrentTransactions.read.available`,
            thresholds: { warning: 10, critical: 5 },
            description: 'Number of available WiredTiger read tickets',
        },
        {
            id: 'wt_write_tickets_available',
            label: 'WiredTiger Write Tickets Available',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().wiredTiger.concurrentTransactions.write.available`,
            thresholds: { warning: 5, critical: 2 },
            description: 'Number of available WiredTiger write tickets',
        },
        {
            id: 'page_faults_per_sec',
            label: 'Page Faults/sec',
            unit: 'faults/s',
            category: 'performance',
            query: `db.serverStatus().extra_info.page_faults / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Page faults per second',
        },
        {
            id: 'anomalies_24h',
            label: 'Anomalies (24h)',
            unit: 'count',
            category: 'performance',
            query: `db.system.profile.find({ts: {$gt: new Date(Date.now() - 86400000)}, millis: {$gt: 1000}}).count()`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Detected performance anomalies in last 24 hours',
        },
        // ===== STORAGE CATEGORY =====
        {
            id: 'total_indexes',
            label: 'Total Indexes',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].getIndexes().length, 0)`,
            thresholds: { warning: 500, critical: 1000 },
            description: 'Total number of indexes across all collections',
        },
        {
            id: 'unused_indexes',
            label: 'Unused Indexes',
            unit: 'count',
            category: 'storage',
            query: `db.aggregate([{$indexStats: {}}, {$match: {accesses: {$exists: false}}}]).toArray().length`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Number of indexes that have never been used',
        },
        {
            id: 'collscan_percent',
            label: 'Collection Scan Percentage',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().metrics.query.scannedObjects / (db.serverStatus().metrics.query.scannedObjects + db.serverStatus().metrics.query.scannedCollections) * 100) || 0`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of queries without proper indexes',
        },
        {
            id: 'est_index_savings_mb',
            label: 'Est. Index Savings',
            unit: 'MB',
            category: 'storage',
            query: `db.aggregate([{$indexStats: {}}, {$match: {accesses: {$exists: false}}}, {$group: {_id: null, totalSize: {$sum: '$size'}}}]).next().totalSize / 1048576 || 0`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Estimated storage savings from removing unused indexes',
        },
        {
            id: 'total_collections',
            label: 'Total Collections',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().filter(name => !name.startsWith('system.')).length`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of user collections in database',
        },
        {
            id: 'total_documents',
            label: 'Total Documents',
            unit: 'count',
            category: 'storage',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].count(), 0)`,
            thresholds: { warning: 100000000, critical: 500000000 },
            description: 'Total number of documents across all collections',
        },
        {
            id: 'total_data_size_bytes',
            label: 'Data Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().dataSize`,
            thresholds: { warning: 10737418240, critical: 21474836480 },
            description: 'Total data size across all collections (10GB warning, 20GB critical)',
        },
        {
            id: 'total_index_size_bytes',
            label: 'Index Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().indexSize`,
            thresholds: { warning: 5368709120, critical: 10737418240 },
            description: 'Total size of all indexes (5GB warning)',
        },
        {
            id: 'wt_cache_size_bytes',
            label: 'WiredTiger Cache Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.cache.maximum_bytes_configured`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Configured WiredTiger cache size',
        },
        {
            id: 'wt_cache_used_bytes',
            label: 'WiredTiger Cache Used',
            unit: 'bytes',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.cache.bytes_currently_in_the_cache`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Currently used WiredTiger cache size',
        },
        {
            id: 'wt_dirty_pages_percent',
            label: 'WiredTiger Dirty Pages',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().wiredTiger.cache.pages_currently_dirty / db.serverStatus().wiredTiger.cache.pages_in_cache * 100) || 0`,
            thresholds: { warning: 50, critical: 80 },
            description: 'Percentage of WiredTiger cache pages that are dirty',
        },
        {
            id: 'wt_cache_hit_ratio',
            label: 'WiredTiger Cache Hit Ratio',
            unit: '%',
            category: 'storage',
            query: `(db.serverStatus().wiredTiger.cache.pages_requested_from_the_cache / (db.serverStatus().wiredTiger.cache.pages_requested_from_the_cache + db.serverStatus().wiredTiger.cache.pages_read_into_cache) * 100) || 0`,
            thresholds: { warning: 80, critical: 60 },
            description: 'Cache hit ratio for WiredTiger storage engine',
        },
        {
            id: 'last_backup_age_hours',
            label: 'Last Backup Age',
            unit: 'hours',
            category: 'storage',
            query: `(Date.now() - db.admin.command({fsync: 1, async: false}).lastBackupTime) / 3600000 || 0`,
            thresholds: { warning: 24, critical: 72 },
            description: 'Hours since last successful backup',
        },
        {
            id: 'backup_size_bytes',
            label: 'Last Backup Size',
            unit: 'bytes',
            category: 'storage',
            query: `db.stats().dataSize + db.stats().indexSize`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Size of last backup (estimated from data+index size)',
        },
        {
            id: 'storage_growth_per_month_bytes',
            label: 'Monthly Storage Growth',
            unit: 'bytes/month',
            category: 'storage',
            query: `(db.stats().dataSize + db.stats().indexSize) / ((Date.now() - db.stats().serverTime) / (1000 * 60 * 60 * 24 * 30)) || 0`,
            thresholds: { warning: 1073741824, critical: 5368709120 },
            description: 'Average monthly storage growth rate',
        },
        {
            id: 'days_until_disk_full',
            label: 'Days Until Disk Full',
            unit: 'days',
            category: 'storage',
            query: `999`,
            thresholds: { warning: 30, critical: 7 },
            description: 'Estimated days before disk runs out of space (requires system metrics)',
        },
        {
            id: 'ops_growth_per_month',
            label: 'Monthly Ops Growth',
            unit: '%',
            category: 'storage',
            query: `((db.serverStatus().opcounters.total || 0) / ((Date.now() - db.stats().serverTime) / (1000 * 60 * 60 * 24 * 30))) || 0`,
            thresholds: { warning: 20, critical: 50 },
            description: 'Percentage monthly growth in operation volume',
        },
        // ===== REPLICATION CATEGORY =====
        {
            id: 'repl_lag_sec',
            label: 'Replication Lag',
            unit: 'seconds',
            category: 'replication',
            query: `rs.status().members.reduce((max, m) => Math.max(max, m.optime?.ts?.getTime ? (new Date() - m.optime.ts) / 1000 : 0), 0)`,
            thresholds: { warning: 5, critical: 30 },
            description: 'Maximum replication lag across replica set members',
        },
        {
            id: 'oplog_window_hours',
            label: 'Oplog Window',
            unit: 'hours',
            category: 'replication',
            query: `(db.oplog.rs.find().max().ts.getTime() - db.oplog.rs.find().min().ts.getTime()) / 3600000`,
            thresholds: { warning: 24, critical: 12 },
            description: 'Hours of operations stored in oplog (12 hour warning)',
        },
        {
            id: 'elections_7d',
            label: 'Elections (7d)',
            unit: 'count',
            category: 'replication',
            query: `db.admin.command({serverStatus: 1}).repl.electionCandidateMetrics?.electionCount || 0`,
            thresholds: { warning: 2, critical: 5 },
            description: 'Number of elections in last 7 days',
        },
        {
            id: 'failover_ready',
            label: 'Failover Ready',
            unit: 'boolean',
            category: 'replication',
            query: `rs.status().members.filter(m => m.health === 1 && m.state !== 1).length >= 1 ? 1 : 0`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Whether cluster is ready for automatic failover',
        },
        {
            id: 'shard_count',
            label: 'Shard Count',
            unit: 'count',
            category: 'replication',
            query: `sh.status().shards.length`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Number of shards in the cluster',
        },
        {
            id: 'chunks_total',
            label: 'Total Chunks',
            unit: 'count',
            category: 'replication',
            query: `db.getSiblingDB('config').chunks.count()`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Total number of chunks across all shards',
        },
        {
            id: 'balanced_percent',
            label: 'Chunk Balance',
            unit: '%',
            category: 'replication',
            query: `100`,
            thresholds: { warning: 90, critical: 80 },
            description: 'Percentage of even chunk distribution across shards',
        },
        {
            id: 'oplog_entries_per_sec',
            label: 'Oplog Entries/sec',
            unit: 'entries/s',
            category: 'replication',
            query: `db.oplog.rs.count() / ((db.stats().serverTime - db.oplog.rs.find().min().ts.getTime() / 1000) || 1)`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Number of oplog entries created per second',
        },
        // ===== DATA CATEGORY =====
        {
            id: 'document_count',
            label: 'Document Count',
            unit: 'count',
            category: 'data',
            query: `db.getCollectionNames().reduce((sum, coll) => sum + db[coll].estimatedDocumentCount(), 0)`,
            thresholds: { warning: 100000000, critical: 500000000 },
            description: 'Total number of documents in database',
        },
        {
            id: 'avg_document_size_bytes',
            label: 'Avg Document Size',
            unit: 'bytes',
            category: 'data',
            query: `db.stats().dataSize / (db.getCollectionNames().reduce((sum, coll) => sum + db[coll].estimatedDocumentCount(), 0) || 1)`,
            thresholds: { warning: 16384, critical: 65536 },
            description: 'Average document size across all collections',
        },
        // ===== CURSORS & SESSIONS =====
        {
            id: 'cursor_open_total',
            label: 'Open Cursors',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().metrics.cursor.open.total`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Total number of open cursors',
        },
        {
            id: 'cursor_timed_out',
            label: 'Cursors Timed Out',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().metrics.cursor.timedOut`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Total cursors that have timed out since startup',
        },
        {
            id: 'cursor_no_timeout',
            label: 'Cursors (No Timeout)',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().metrics.cursor.open.noTimeout`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Cursors with no timeout flag set (potential leaks)',
        },
        // ===== TRANSACTIONS =====
        {
            id: 'transactions_active',
            label: 'Active Transactions',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().transactions?.currentActive || 0`,
            thresholds: { warning: 50, critical: 100 },
            description: 'Number of currently active multi-document transactions',
        },
        {
            id: 'transactions_committed',
            label: 'Transactions Committed',
            unit: 'count',
            category: 'data',
            query: `db.serverStatus().transactions?.totalCommitted || 0`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total committed multi-document transactions since startup',
        },
        {
            id: 'transactions_aborted',
            label: 'Transactions Aborted',
            unit: 'count',
            category: 'data',
            query: `db.serverStatus().transactions?.totalAborted || 0`,
            thresholds: { warning: 10, critical: 50 },
            description: 'Total aborted multi-document transactions since startup',
        },
        // ===== ASSERTS & ERRORS =====
        {
            id: 'asserts_regular',
            label: 'Regular Asserts',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().asserts.regular`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Number of regular assert events since startup',
        },
        {
            id: 'asserts_warning',
            label: 'Warning Asserts',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().asserts.warning`,
            thresholds: { warning: 5, critical: 20 },
            description: 'Number of warning assert events since startup',
        },
        {
            id: 'asserts_msg',
            label: 'Message Asserts',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().asserts.msg`,
            thresholds: { warning: 1, critical: 10 },
            description: 'Number of message assert events since startup',
        },
        // ===== NETWORK (EXTENDED) =====
        {
            id: 'network_connections_created',
            label: 'Connections Created/sec',
            unit: 'conns/s',
            category: 'overview',
            query: `db.serverStatus().connections.totalCreated / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Rate of new connections created per second',
        },
        {
            id: 'network_requests',
            label: 'Network Requests',
            unit: 'count',
            category: 'performance',
            query: `db.serverStatus().network.numRequests`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total network requests received by server',
        },
        // ===== WIREDTIGER (EXTENDED) =====
        {
            id: 'wt_evictions_per_sec',
            label: 'WiredTiger Evictions/sec',
            unit: 'pages/s',
            category: 'storage',
            query: `(db.serverStatus().wiredTiger.cache.pages_evicted || 0) / db.serverStatus().uptime`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Pages evicted from WiredTiger cache per second',
        },
        {
            id: 'wt_modified_evicted',
            label: 'Modified Pages Evicted',
            unit: 'count',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.cache['modified pages evicted'] || 0`,
            thresholds: { warning: 100, critical: 500 },
            description: 'Modified pages evicted from cache (forces disk writes)',
        },
        {
            id: 'wt_log_bytes_written',
            label: 'WiredTiger Log Written',
            unit: 'bytes',
            category: 'storage',
            query: `db.serverStatus().wiredTiger.log['log bytes written'] || 0`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total bytes written to WiredTiger journal log',
        },
        // ===== TTL & CHANGE STREAMS =====
        {
            id: 'ttl_deletes_per_sec',
            label: 'TTL Deletes/sec',
            unit: 'docs/s',
            category: 'data',
            query: `(db.serverStatus().metrics.ttl?.deletedDocuments || 0) / db.serverStatus().uptime`,
            thresholds: { warning: 1000, critical: 5000 },
            description: 'Documents deleted by TTL indexes per second',
        },
        {
            id: 'ttl_passes',
            label: 'TTL Passes',
            unit: 'count',
            category: 'data',
            query: `db.serverStatus().metrics.ttl?.passes || 0`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total number of TTL background thread passes',
        },
        // ===== GLOBAL LOCK =====
        {
            id: 'global_lock_total_time',
            label: 'Global Lock Time',
            unit: 'ms',
            category: 'performance',
            query: `db.serverStatus().globalLock.totalTime / 1000`,
            thresholds: { warning: 0, critical: 0 },
            description: 'Total time the global lock has been held',
        },
        {
            id: 'global_lock_active_clients_total',
            label: 'Active Clients Total',
            unit: 'count',
            category: 'overview',
            query: `db.serverStatus().globalLock.activeClients.total`,
            thresholds: { warning: 100, critical: 200 },
            description: 'Total active clients performing operations',
        },
    ],
};

/**
 * Get metric definitions for a specific database type
 */
export function getMetricsForDbType(dbType) {
    return METRIC_DEFINITIONS[dbType] || [];
}

/**
 * Get all unique categories across all database types
 */
export function getAllCategories() {
    const categories = new Set();
    Object.values(METRIC_DEFINITIONS).forEach(metrics => {
        metrics.forEach(m => categories.add(m.category));
    });
    return Array.from(categories).sort();
}

/**
 * Get metrics that are common to all database types
 */
export function getUniversalMetrics() {
    return {
        connections: 'active_connections',
        storage: 'db_size',
        performance: 'cache_hit_ratio',
    };
}

/**
 * Evaluate metric health based on thresholds
 * Returns: { status: 'ok'|'warning'|'critical', value, threshold }
 */
export function evaluateMetricHealth(metricId, value, dbType) {
    const metrics = getMetricsForDbType(dbType);
    const metric = metrics.find(m => m.id === metricId);

    if (!metric) {
        return { status: 'unknown', value, threshold: null };
    }

    const { thresholds } = metric;

    // For most metrics, lower is better (except hit ratios and percentages)
    const isInverted = metric.id.includes('ratio') || metric.id.includes('hit') || metric.id === 'cache_usage';

    if (isInverted) {
        // Higher is better
        if (value <= thresholds.critical) {
            return { status: 'critical', value, threshold: thresholds.critical };
        }
        if (value <= thresholds.warning) {
            return { status: 'warning', value, threshold: thresholds.warning };
        }
        return { status: 'ok', value, threshold: null };
    } else {
        // Lower is better
        if (value >= thresholds.critical) {
            return { status: 'critical', value, threshold: thresholds.critical };
        }
        if (value >= thresholds.warning) {
            return { status: 'warning', value, threshold: thresholds.warning };
        }
        return { status: 'ok', value, threshold: null };
    }
}

/**
 * Get metric by ID and database type
 */
export function getMetricById(metricId, dbType) {
    const metrics = getMetricsForDbType(dbType);
    return metrics.find(m => m.id === metricId);
}

/**
 * Get metrics by category
 */
export function getMetricsByCategory(category, dbType) {
    const metrics = getMetricsForDbType(dbType);
    return metrics.filter(m => m.category === category);
}
