{{- if and .Values.observability.prometheusScrape (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fathom.fullname" . }}
  labels:
    {{- include "fathom.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fathom.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end -}}
